server:
  port: 8080

spring:
  profiles: prod
  
app:
  welcomeMessage: Welcome to the Document Service Application!
  name: Document Service Application
  description: ${app.name} is a Spring Boot application


file:
  path: /path/to/your/files
  
  
azure:
  storage:
    connection-string: <your-azure-connection-string>
    container-name: <your-container-name>
